PS_Store/Controllers/AppetizersController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PS_Store.Models;

namespace PS_Store.Controllers
{
    public class AppetizersController : Controller
    {
        private PSStoreContext db = new PSStoreContext();

        // GET: Appetizers
        public ActionResult Index()
        {
            return View(db.Appetizers.ToList());
        }

        // GET: Appetizers/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Appetizer appetizer = db.Appetizers.Find(id);
            if (appetizer == null)
            {
                return HttpNotFound();
            }
            return View(appetizer);
        }

        // GET: Appetizers/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Appetizers/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Category,Name,ShortDescription,LongDescription,ThumbnailImage,FullImage,Price")] Appetizer appetizer)
        {
            if (ModelState.IsValid)
            {
                db.Appetizers.Add(appetizer);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(appetizer);
        }

        // GET: Appetizers/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Appetizer appetizer = db.Appetizers.Find(id);
            if (appetizer == null)
            {
                return HttpNotFound();
            }
            return View(appetizer);
        }

        // POST: Appetizers/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Category,Name,ShortDescription,LongDescription,ThumbnailImage,FullImage,Price")] Appetizer appetizer)
        {
            if (ModelState.IsValid)
            {
                db.Entry(appetizer).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(appetizer);
        }

        // GET: Appetizers/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Appetizer appetizer = db.Appetizers.Find(id);
            if (appetizer == null)
            {
                return HttpNotFound();
            }
            return View(appetizer);
        }

        // POST: Appetizers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Appetizer appetizer = db.Appetizers.Find(id);
            db.Appetizers.Remove(appetizer);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PS_Store/Controllers/DimSumsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PS_Store.Models;

namespace PS_Store.Controllers
{
    public class DimSumsController : Controller
    {
        private PSStoreContext db = new PSStoreContext();

        // GET: DimSums
        public ActionResult Index()
        {
            return View(db.DimSums.ToList());
        }

        // GET: DimSums/Details/5
        public ActionResult Details(int? id)
        {
            // dimsums/details is not valid
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DimSum dimSum = db.DimSums.Find(id);
            if (dimSum == null)
            {
                return HttpNotFound();
            }
            return View(dimSum);
        }

        // GET: DimSums/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: DimSums/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Category,Name,ShortDescription,LongDescription,ThumbnailImage,FullImage,Price")] DimSum dimSum)
        {
            if (ModelState.IsValid)
            {
                db.DimSums.Add(dimSum);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(dimSum);
        }

        // GET: DimSums/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DimSum dimSum = db.DimSums.Find(id);
            if (dimSum == null)
            {
                return HttpNotFound();
            }
            return View(dimSum);
        }

        // POST: DimSums/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Category,Name,ShortDescription,LongDescription,ThumbnailImage,FullImage,Price")] DimSum dimSum)
        {
            if (ModelState.IsValid)
            {
                db.Entry(dimSum).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(dimSum);
        }

        // GET: DimSums/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DimSum dimSum = db.DimSums.Find(id);
            if (dimSum == null)
            {
                return HttpNotFound();
            }
            return View(dimSum);
        }

        // POST: DimSums/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DimSum dimSum = db.DimSums.Find(id);
            db.DimSums.Remove(dimSum);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PS_Store/Controllers/EntreesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PS_Store.Models;

namespace PS_Store.Controllers
{
    public class EntreesController : Controller
    {
        private PSStoreContext db = new PSStoreContext();

        // GET: Entrees
        public ActionResult Index()
        {
            return View(db.Entrees.ToList());
        }

        // GET: Entrees/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Entree entree = db.Entrees.Find(id);
            if (entree == null)
            {
                return HttpNotFound();
            }
            return View(entree);
        }

        // GET: Entrees/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Entrees/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Category,Name,ShortDescription,LongDescription,ThumbnailImage,FullImage,Price")] Entree entree)
        {
            if (ModelState.IsValid)
            {
                db.Entrees.Add(entree);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(entree);
        }

        // GET: Entrees/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Entree entree = db.Entrees.Find(id);
            if (entree == null)
            {
                return HttpNotFound();
            }
            return View(entree);
        }

        // POST: Entrees/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Category,Name,ShortDescription,LongDescription,ThumbnailImage,FullImage,Price")] Entree entree)
        {
            if (ModelState.IsValid)
            {
                db.Entry(entree).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(entree);
        }

        // GET: Entrees/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Entree entree = db.Entrees.Find(id);
            if (entree == null)
            {
                return HttpNotFound();
            }
            return View(entree);
        }

        // POST: Entrees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Entree entree = db.Entrees.Find(id);
            db.Entrees.Remove(entree);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PS_Store/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PS_Store.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

PS_Store/Controllers/SoupsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PS_Store.Models;

namespace PS_Store.Controllers
{
    public class SoupsController : Controller
    {
        private PSStoreContext db = new PSStoreContext();

        // GET: Soups
        public ActionResult Index()
        {
            return View(db.Soups.ToList());
        }

        // GET: Soups/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Soup soup = db.Soups.Find(id);
            if (soup == null)
            {
                return HttpNotFound();
            }
            return View(soup);
        }

        // GET: Soups/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Soups/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Category,Name,ShortDescription,LongDescription,ThumbnailImage,FullImage,Price")] Soup soup)
        {
            if (ModelState.IsValid)
            {
                db.Soups.Add(soup);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(soup);
        }

        // GET: Soups/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Soup soup = db.Soups.Find(id);
            if (soup == null)
            {
                return HttpNotFound();
            }
            return View(soup);
        }

        // POST: Soups/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Category,Name,ShortDescription,LongDescription,ThumbnailImage,FullImage,Price")] Soup soup)
        {
            if (ModelState.IsValid)
            {
                db.Entry(soup).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(soup);
        }

        // GET: Soups/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Soup soup = db.Soups.Find(id);
            if (soup == null)
            {
                return HttpNotFound();
            }
            return View(soup);
        }

        // POST: Soups/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Soup soup = db.Soups.Find(id);
            db.Soups.Remove(soup);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PS_Store/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h1>About Us</h1>
<h2></h2>

<img alt="Box" height="300" src="~/Box.jpg" style="float: right" width="300">
<p>PS_Store aims to provide the most unique variety of food options to the global market. We will provide on-demand sweet services while customer were waiting their food. 
</p>
<p>Since its inception in 1996, the PS_Store has continued to earn parise for its consistent delivery of the chinese food and setting at competitive prices. In fact, despite the growth of the PS_Store franchise chain over the years, we’ve remained dedicated and true to the core business principles of the first ever PS_Store location.</p>
<p>Business Rules</p>
<p>Customer must be over 19 years old to get the Alcoholic beverage</p>
<p>Membership can enjoy 10% discount when making payment</p>
<p>Business Rules for employee</p>
<p>Keep the work clothes tidy and uniform every day</p>
<p>Be polite to every guest</p>
<p>Services should be treated equally</p>

PS_Store/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>Contact Us</h2>
<h3>More information of our store</h3>

<address>
    42 Glendennan Avenue<br />
    Markham, ON <br />
    <abbr title="Phone">P:</abbr>
    416-777-7877
</address>
<h1><img alt="Address.png" src="~/Address.PNG" height="400" width="700" /></h1>

<address>
    <strong>Customer Service:</strong>   <a href="mailto:Support@example.com">PSResturant@Gamil.com</a><br />
    <strong>Take out :</strong> <a href="mailto:Marketing@example.com">TaOtPs@Gmail.com</a>
</address>

PS_Store/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}
<div class="jumbotron">
    <h1>Soups</h1>
    <img alt="Soup" height="285" src="~/SoupHome.jpg" style="float: right" width="428">
    <p>Soup is a primarily liquid food, generally served warm or hot, that is made by combining ingredients such as meat and vegetables with stock, juice, water, or another liquid. Hot soups are additionally characterized by boiling solid ingredients in liquids in a pot until the flavors are extracted, forming a broth.</p>
    <p><a class="btn btn-primary btn-lg" href="@Url.Action("Index", "Soups")" role="button">Learn more</a></p>
</div>
<div class="jumbotron">
    <h1>Appetizer</h1>
    <img alt="Appetizer" height="285" src="~/AppetizerHome.jpg" style="float: right" width="428">
    <p>An hors d'oeuvre, appetizer, or starter is a small dish served before a meal. Some hors d'oeuvres are served cold, others hot. Hors d'oeuvres may be served at the dinner table as a part of the meal, or they may be served before seating. Formerly, hors d'oeuvres were also served between courses.</p>
    <p><a class="btn btn-primary btn-lg" href="@Url.Action("Index", "Appetizers")" role="button">Learn more</a></p>
</div>
<div class="jumbotron">
    <h1>Entrees</h1>
    <img alt="Entree" height="285" src="~/Entreehome.jpg" style="float: right" width="428">
    <p>The main course is the featured or primary dish in a meal consisting of several courses. It usually follows the entrée ("entry") course. In the United States and parts of Canada, it may be called "entrée". In china, entree will always include chicken, beef, pork and so on. In China, every meal should have at least one entree to show the respect to the guest</p>
    <p><a class="btn btn-primary btn-lg" href="@Url.Action("Index", "Entrees")" role="button">Learn more</a></p>
</div>
<div class="jumbotron">
    <h1>Dim Sum</h1>
    <img alt="DimSum" height="285" src="~/DimSumHome.jpg" style="float: right" width="428">
    <p>Dim Sum is a style of Chinese cuisine (particularly Cantonese but also other varieties) prepared as small bite-sized portions of food served in small steamer baskets or on small plates. Dim sum dishes are usually served with tea, together formed a full tea brunch. Dimsums is one of the famous food in China, every people in GuangDong will go to DimSum store at least twice a week.</p>
    <p><a class="btn btn-primary btn-lg" href="@Url.Action("Index", "DimSums")" role="button">Learn more</a></p>
</div>