PS_Store/Controllers/DimSumsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PS_Store.Models;

namespace PS_Store.Controllers
{
    public class DimSumsController : Controller
    {
        private PSStoreContext db = new PSStoreContext();

        // GET: DimSums
        public ActionResult Index()
        {
            return View(db.DimSums.ToList());
        }

        // GET: DimSums/Details/5
        public ActionResult Details(int? id)
        {
            // dimsums/details is not valid
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DimSum dimSum = db.DimSums.Find(id);
            if (dimSum == null)
            {
                return HttpNotFound();
            }
            return View(dimSum);
        }

        // GET: DimSums/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: DimSums/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Category,Name,ShortDescription,LongDescription,ThumbnailImage,FullImage,Price")] DimSum dimSum)
        {
            if (ModelState.IsValid)
            {
                db.DimSums.Add(dimSum);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(dimSum);
        }

        // GET: DimSums/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DimSum dimSum = db.DimSums.Find(id);
            if (dimSum == null)
            {
                return HttpNotFound();
            }
            return View(dimSum);
        }

        // POST: DimSums/Edit/5
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Category,Name,ShortDescription,LongDescription,ThumbnailImage,FullImage,Price")] DimSum dimSum)
        {
            if (ModelState.IsValid)
            {
                db.Entry(dimSum).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(dimSum);
        }

        // GET: DimSums/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            DimSum dimSum = db.DimSums.Find(id);
            if (dimSum == null)
            {
                return HttpNotFound();
            }
            return View(dimSum);
        }

        // POST: DimSums/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            DimSum dimSum = db.DimSums.Find(id);
            db.DimSums.Remove(dimSum);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PS_Store/Controllers/EntreesController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PS_Store.Models;

namespace PS_Store.Controllers
{
    public class EntreesController : Controller
    {
        private PSStoreContext db = new PSStoreContext();

        // GET: Entrees
        public ActionResult Index()
        {
            return View(db.Entrees.ToList());
        }

        // GET: Entrees/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Entree entree = db.Entrees.Find(id);
            if (entree == null)
            {
                return HttpNotFound();
            }
            return View(entree);
        }

        // GET: Entrees/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Entrees/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Category,Name,ShortDescription,LongDescription,ThumbnailImage,FullImage,Price")] Entree entree)
        {
            if (ModelState.IsValid)
            {
                db.Entrees.Add(entree);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(entree);
        }

        // GET: Entrees/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Entree entree = db.Entrees.Find(id);
            if (entree == null)
            {
                return HttpNotFound();
            }
            return View(entree);
        }

        // POST: Entrees/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Category,Name,ShortDescription,LongDescription,ThumbnailImage,FullImage,Price")] Entree entree)
        {
            if (ModelState.IsValid)
            {
                db.Entry(entree).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(entree);
        }

        // GET: Entrees/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Entree entree = db.Entrees.Find(id);
            if (entree == null)
            {
                return HttpNotFound();
            }
            return View(entree);
        }

        // POST: Entrees/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Entree entree = db.Entrees.Find(id);
            db.Entrees.Remove(entree);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PS_Store/Controllers/SoupsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PS_Store.Models;

namespace PS_Store.Controllers
{
    public class SoupsController : Controller
    {
        private PSStoreContext db = new PSStoreContext();

        // GET: Soups
        public ActionResult Index()
        {
            return View(db.Soups.ToList());
        }

        // GET: Soups/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Soup soup = db.Soups.Find(id);
            if (soup == null)
            {
                return HttpNotFound();
            }
            return View(soup);
        }

        // GET: Soups/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Soups/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Category,Name,ShortDescription,LongDescription,ThumbnailImage,FullImage,Price")] Soup soup)
        {
            if (ModelState.IsValid)
            {
                db.Soups.Add(soup);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(soup);
        }

        // GET: Soups/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Soup soup = db.Soups.Find(id);
            if (soup == null)
            {
                return HttpNotFound();
            }
            return View(soup);
        }

        // POST: Soups/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Category,Name,ShortDescription,LongDescription,ThumbnailImage,FullImage,Price")] Soup soup)
        {
            if (ModelState.IsValid)
            {
                db.Entry(soup).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(soup);
        }

        // GET: Soups/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Soup soup = db.Soups.Find(id);
            if (soup == null)
            {
                return HttpNotFound();
            }
            return View(soup);
        }

        // POST: Soups/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Soup soup = db.Soups.Find(id);
            db.Soups.Remove(soup);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PS_Store/Controllers/SpecialsController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using PS_Store.Models;

namespace PS_Store.Controllers
{
    public class SpecialsController : Controller
    {
        private PSStoreContext db = new PSStoreContext();

        /// <summary>
        /// GET: Specials
        /// </summary>
        public ActionResult Index()
        {
            return View(db.Specials.ToList());
        }

        /// <summary>
        /// GET: Specials/Details/5
        /// </summary>
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Special special = db.Specials.Find(id);
            if (special == null)
            {
                return HttpNotFound();
            }
            return View(special);
        }

        // GET: Specials/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Specials/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Category,Name,ShortDescription,LongDescription,ThumbnailImage,FullImage,PriceBefore,Price")] Special special)
        {
            if (ModelState.IsValid)
            {
                db.Specials.Add(special);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(special);
        }

        // GET: Specials/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Special special = db.Specials.Find(id);
            if (special == null)
            {
                return HttpNotFound();
            }
            return View(special);
        }

        // POST: Specials/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Category,Name,ShortDescription,LongDescription,ThumbnailImage,FullImage,PriceBefore,Price")] Special special)
        {
            if (ModelState.IsValid)
            {
                db.Entry(special).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(special);
        }

        // GET: Specials/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Special special = db.Specials.Find(id);
            if (special == null)
            {
                return HttpNotFound();
            }
            return View(special);
        }

        // POST: Specials/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Special special = db.Specials.Find(id);
            db.Specials.Remove(special);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

PS_Store/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - PS Restaurant</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
    @Styles.Render("~/Content/fontawesome")


</head>
<body style="background-image: url('.jpg'); background-position: center; background-repeat: repeat-y">
    
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Ps Store", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a href="@Url.Action("Index", "Home")"><i class="fa fa-home fa-lg"></i> Home</a></li>
                    <li><a href="@Url.Action("About", "Home")"><i class="fa fa-info fa-lg"></i> About</a></li>
                    <li><a href="@Url.Action("Contact", "Home")"><i class="fa fa-phone fa-lg"></i> Contact</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <li class="dropdown">
                        <a class="dropdown-toggle" data-toggle="dropdown" href="#"><i class="fa fa-cutlery" aria-hidden="true"></i> 
                            Menu<span class="caret"></span>
                        </a>
                        <ul class="dropdown-menu">
                            <li><a href="@Url.Action("Index", "Soups")">Soup</a></li>
                            <li><a href="@Url.Action("Index", "Appetizers")">Appetizer</a></li>
                            <li><a href="@Url.Action("Index", "Entrees")">Entree</a></li>
                            <li><a href="@Url.Action("Index", "DimSums")">Dim Sum</a></li>
                            <li><a href="@Url.Action("Index", "Specials")">Special</a></li>
                        </ul>
                    </li>                    
                </ul>
            </div>
        </div>
    </div>
<img alt="Banner" src="~/Food.jpg" height="400" width="1253" />
    <div style="background-color:#ffffff; opacity:0.8;background-position: center; background-repeat: repeat-y; color:black; font-family: 'Comic Sans MS'">

        <div class="navbar-inner">
            <div class="container">
                <a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </a>
                <div class="nav-collapse">
                    <ul class="nav nav-justified">
                        <li><a href="@Url.Action("Index", "Soups")">Soup</a></li>
                        <li><a href="@Url.Action("Index", "Appetizers")">Appetizer</a></li>
                        <li><a href="@Url.Action("Index", "Entrees")">Entree</a></li>
                        <li><a href="@Url.Action("Index", "DimSums")">Dim Sum</a></li>
                        <li><a href="@Url.Action("Index", "Specials")">Special</a></li>
                    </ul>
                </div><!--/.nav-collapse -->
            </div><!-- container -->
        </div><!-- navbar-inner -->

        <div class="container body-content">
            @RenderBody()
            <hr />
            <footer>
                <div class="nav-collapse">
                    <ul class="nav nav-justified">
                        <li><a href="@Url.Action("Contact", "Home")"><i class="fa fa-map" aria-hidden="true"></i> CONTACT US</a></li>
                        <li><a href="@Url.Action("Index", "Home")"><i class="fa fa-home fa-lg"></i> Back TO HOME</a></li>
                        <li><a href="@Url.Action("About", "Home")"><i class="fa fa-address-book" aria-hidden="true"></i> ABOUT</a></li>
                    </ul>
                </div><!--/.nav-collapse -->
                <p>&copy; @DateTime.Now.Year - PS Restaurant</p>
            </footer>
        </div>

        @Scripts.Render("~/bundles/jquery")
        @Scripts.Render("~/bundles/bootstrap")
        @RenderSection("scripts", required: false)
    </div>
</body>
</html>